const TEAM_MEMBERS = {
  MENTORS: [
    {
      name: 'Mario Behling',
      github: 'http://github.com/mariobehling',
      avatar: 'mariobehling.jpeg',
      twitter: 'https://twitter.com/mariobehling',
      linkedin: 'https://www.linkedin.com/in/mariobehling/',
      blog: '#',
    },
    {
      name: 'Michael Christen',
      github: 'https://github.com/orbiter',
      avatar: 'Orbiter.jpeg',
      twitter: 'https://twitter.com/0rb1t3r',
      linkedin: 'https://www.linkedin.com/in/orbiter/',
      blog: '#',
    },
  ],
  DEVELOPERS: [
    {
      name: 'Akshat Jain',
      github: 'https://github.com/Akshat-Jain',
      avatar: 'Akshat.jpeg',
      designation: 'Java + Web Developer',
      twitter: 'https://twitter.com/akjn99',
      linkedin: 'https://www.linkedin.com/in/akjn99/',
      blog: '#',
    },
    {
      name: 'Akshat Garg',
      github: 'https://github.com/akshatnitd',
      avatar: 'AkshatGarg.jpeg',
      designation: 'Java + Web Developer',
      twitter: 'https://twitter.com/tweet_akshat',
      linkedin: 'https://www.linkedin.com/in/akshatnitd',
      blog: 'https://aspirewithmeblog.wordpress.com',
    },
    {
      name: 'Ali Ayub Khan',
      github: 'https://github.com/AliAyub007',
      avatar: 'AliAyub.jpeg',
      designation: 'Bot Developer',
      twitter: 'https://twitter.com/ali_ayub007',
      linkedin: 'https://www.linkedin.com/in/ali-ayub-khan-356432117/',
      blog: 'http://blog.fossasia.org/author/AliAyub007/',
    },
    {
      name: 'Amit Tiwary',
      github: 'https://github.com/amitiwary999',
      avatar: 'Amith.jpeg',
      designation: 'Android Developer',
      twitter: '#',
      linkedin: 'https://www.linkedin.com/in/amit-tiwary-8bb081103',
      blog: 'http://blog.fossasia.org/author/amitiwary999/',
    },
    {
      name: 'Anshuman Verma',
      github: 'https://github.com/anshumanv',
      avatar: 'anshumanv.jpeg',
      designation: 'Web Developer',
      twitter: 'https://twitter.com/Anshumaniac12',
      linkedin: 'https://www.linkedin.com/in/anshumanv12',
    },
    {
      name: 'Anup Kumar Panwar',
      github: 'https://github.com/anupkumarpanwar',
      avatar: 'Anup.jpeg',
      designation: 'Android Developer | Full Stack Developer',
      twitter: 'https://twitter.com/anupkumarpanwar',
      linkedin: 'https://www.linkedin.com/in/anupkumarpanwar',
      blog: '#',
    },
    {
      name: 'Arundhati Gupta',
      github: 'https://github.com/arundhati24',
      avatar: 'Arundhati.jpeg',
      designation: 'Android Developer',
      twitter: 'https://twitter.com/gupta_arundhati',
      linkedin: 'https://www.linkedin.com/in/gupta-arundhati/',
      blog: '#',
    },
    {
      name: 'Chashmeet Singh',
      github: 'http://github.com/chashmeetsingh',
      avatar: 'ChashmeetSingh.jpeg',
      designation: 'iOS Developer',
      twitter: 'https://twitter.com/CChashmeetsingh',
      linkedin: 'https://www.linkedin.com/in/chashmeet/',
      blog: 'http://blog.fossasia.org/author/chashmeetsingh/',
    },

    {
      name: 'Chetan Kaushik',
      github: 'https://github.com/dynamitechetan',
      avatar: 'Chetan.jpeg',
      designation: 'Java + Web Developer',
      twitter: 'https://twitter.com/DynamiteChetan',
      linkedin: 'https://www.linkedin.com/in/chetankaushik/',
      blog: 'http://blog.fossasia.org/author/dynamitechetan/',
    },
    {
      name: 'Chirag Wadhera',
      github: 'https://github.com/chiragw15',
      avatar: 'Chirag.jpeg',
      designation: 'Android Developer',
      twitter: ' https://twitter.com/chiragw15',
      linkedin: ' https://www.linkedin.com/in/chirag-wadhera-155b22106/',
      blog: 'http://blog.fossasia.org/author/chiragw15/',
    },

    {
      name: 'Divyanshu N Singh',
      github: 'https://github.com/DNS-404',
      avatar: 'DivyanshuNSingh.jpeg',
      designation: 'Bot + Web Developer',
      twitter: 'https://twitter.com/DivyanshuNSingh',
      linkedin: 'https://www.linkedin.com/in/divyanshunsingh/',
      blog: '#',
    },
    {
      name: 'Dravit Lochan Gupta',
      github: 'https://github.com/DravitLochan',
      avatar: 'DravitLochan.jpeg',
      designation: 'Java + Web Developer',
      twitter: 'https://twitter.com/DravitLochan',
      linkedin: '#',
      blog: 'http://blog.fossasia.org/author/DravitLochan/',
    },
    {
      name: 'Harshit Dwivedi',
      github: 'https://github.com/the-dagger',
      avatar: 'HarshitDwivedi.jpeg',
      designation: 'Main Contributor',
      twitter: 'https://twitter.com/daggerdwivedi',
      linkedin: 'https://www.linkedin.com/in/hadwivedi/?ppe=1',
      blog: '#',
    },
    {
      name: 'Harshit Kedia',
      github: 'https://github.com/hkedia321',
      avatar: 'HarshitKedia.jpeg',
      designation: 'Bot + Web Developer',
      twitter: 'https://twitter.com/Harshitkedia32',
      linkedin: 'https://www.linkedin.com/in/harshit-kedia-7abb7b108/',
      blog: '#',
    },
    {
      name: 'Isuru Abeywardana',
      github: 'https://github.com/isuruAb',
      avatar: 'IsuruAb.jpeg',
      designation: 'React JS Developer',
      twitter: 'https://twitter.com/isuruAb',
      linkedin: 'https://www.linkedin.com/in/isuruab/',
      blog: 'http://blog.fossasia.org/author/isuruab/',
    },
    {
      name: 'Jogendra Kumar',
      github: 'http://github.com/jogendra',
      avatar: 'Jogendra.jpeg',
      designation: 'iOS Developer',
      twitter: 'https://twitter.com/imjog24',
      linkedin: 'https://www.linkedin.com/in/jogendrasingh24/',
      blog: 'https://jogendra.github.io/',
    },

    {
      name: 'Madhav Rathi',
      github: 'https://github.com/madhavrathi',
      avatar: 'Madhav.jpeg',
      designation: 'React JS Developer',
      twitter: 'https://twitter.com/mdhvrthi',
      linkedin: 'https://www.linkedin.com/in/madhav-rathi-120b57129/',
      blog: 'http://blog.fossasia.org/author/madhavrathi/',
    },

    {
      name: 'Mohit Kumar',
      github: 'https://github.com/batbrain7',
      avatar: 'Mohit.jpeg',
      designation: 'Android Developer',
      twitter: 'https://twitter.com/kumarmohit97',
      linkedin: 'https://www.linkedin.com/in/mohit-kumar-a793a0135/',
      blog: '#',
    },
    {
      name: 'Praduman Pannu',
      github: 'https://github.com/PrP-11',
      avatar: 'PradumanPannu.jpeg',
      designation: 'Java + Web Developer',
      twitter: 'https://twitter.com/praduman_pannu',
      linkedin: 'https://www.linkedin.com/in/praduman-pannu-1409a475',
    },

    {
      name: 'Rishi Raj',
      github: 'http://github.com/rishiraj824',
      avatar: 'RishiRaj.jpeg',
      designation: 'React JS Developer',
      twitter: 'https://twitter.com/rishirajloyola',
      linkedin: 'https://www.linkedin.com/in/rajrishime/',
      blog: 'http://blog.fossasia.org/author/rishiraj824/',
    },

    {
      name: 'Sanskar Jethi',
      github: 'https://github.com/stealthanthrax',
      avatar: 'Sanskar.jpeg',
      designation: 'Full Stack Engineer',
      twitter: 'https://twitter.com/sansyrox',
      linkedin: 'https://www.linkedin.com/in/sanskar-jethi-68b95b48/',
      blog: '#',
    },
    {
      name: 'Saurabh Jain',
      github: 'https://github.com/saurabhjn76',
      avatar: 'Saurabh.jpeg',
      designation: 'Java + Web Developer',
      twitter: '#',
      linkedin: '#',
      blog: 'http://blog.fossasia.org/author/saurabhjn76/',
    },
    {
      name: 'Sudheesh Singanamalla',
      github: 'https://github.com/sudheesh001',
      avatar: 'Sudheesh.jpeg',
      designation: 'Main Contributor',
      twitter: 'https://twitter.com/sudheesh001',
      linkedin: 'https://www.linkedin.com/in/sudheesh001/',
      blog: '#',
    },

    {
      name: 'Wai Gie Kok',
      github: 'http://github.com/woshikie',
      avatar: 'Waigie.jpeg',
      designation: 'Full Stack Developer',
      twitter: 'https://twitter.com/kwaigie',
      linkedin: 'https://www.linkedin.com/in/waigiekok/',
      blog: '#',
    },
    {
      name: 'Wei Tat Chung',
      github: 'http://github.com/cweitat',
      avatar: 'Weitat.jpeg',
      designation: 'Full Stack Developer',
      twitter: 'https://twitter.com/cweitat',
      linkedin: 'https://www.linkedin.com/in/cweitat/',
      blog: '#',
    },
  ],
  ALUMNIS: [
    {
      name: 'Damini Satya',
      github: 'https://github.com/daminisatya',
      avatar: 'Damini.jpeg',
      designation: 'Main Contributor',
      twitter: 'https://twitter.com/Daminisatya',
      linkedin: 'https://www.linkedin.com/in/damini-satya-52816886/',
      blog: '#',
    },
    {
      name: 'Jigyasa Grover',
      github: 'https://github.com/jigyasa-grover',
      avatar: 'JigyasaGrover.jpeg',
      designation: 'Main Contributor',
      twitter: 'https://twitter.com/jigyasa_grover',
      linkedin: '#',
      blog: '#',
    },
    {
      name: 'Jyothir Aditya',
      github: 'https://github.com/jyoth1raditya',
      avatar: 'jyoth1raditya.jpeg',
      designation: 'Java + Web Developer',
      twitter: '#',
      linkedin: '#',
      blog: 'http://blog.fossasia.org/author/jyoth1raditya/',
    },
    {
      name: 'Manveer Singh',
      github: 'https://github.com/Manveer695',
      avatar: 'Manveer.jpeg',
      designation: 'Bot Developer',
      twitter: '#',
      linkedin: '#',
      blog: 'http://blog.fossasia.org/author/Manveer695/',
    },
    {
      name: 'Mayank Tripathi',
      github: 'https://github.com/mayank408',
      avatar: 'Mayank.jpeg',
      designation: 'Android Developer',
      twitter: 'https://twitter.com/mayank_trp408',
      linkedin: 'https://www.linkedin.com/in/mayank-tripathi-a49563126/',
      blog: 'http://blog.fossasia.org/author/mayank408/',
    },
    {
      name: 'Niranjan Rajendran',
      github: 'https://github.com/niranjan94',
      avatar: 'NiranjanRajendran.jpeg',
      designation: 'Main Contributor',
      twitter: 'https://twitter.com/niranjan94',
      linkedin: 'https://www.linkedin.com/in/niranjan94/',
      blog: '#',
    },
    {
      name: 'Pranjal Paliwal',
      github: 'https://github.com/betterclever',
      avatar: 'Pranjal.jpeg',
      designation: 'IoT + Web developer',
      twitter: 'https://twitter.com/TheBetterClever',
      linkedin: 'https://linkedin.com/in/betterclever',
      blog: 'http://blog.fossasia.org/author/betterclever/',
    },
    {
      name: 'Uday Theja',
      github: 'https://github.com/uday96',
      avatar: 'Udaytheja.jpeg',
      designation: 'React JS Developer',
      twitter: 'https://twitter.com/udayteja96',
      linkedin: 'https://www.linkedin.com/in/uday-theja/',
      blog: 'http://blog.fossasia.org/author/uday96/',
    },
  ],

  MANAGERS: [
    {
      name: 'Eden Dang',
      github: '#',
      avatar: 'Eden.jpeg',
      designation: 'Event Manager',
      twitter: 'https://twitter.com/edendang211',
      linkedin: 'https://www.linkedin.com/in/dangphuchau/',
      blog: '#',
    },
    {
      name: 'Hong Phuc Dang',
      github: 'https://github.com/hpdang',
      avatar: 'hpdang.jpeg',
      designation: 'Community and Project Manager',
      twitter: 'https://twitter.com/hpdang',
      linkedin: 'https://www.linkedin.com/in/hongphucdang/',
      blog: '#',
    },
  ],
};

export default TEAM_MEMBERS;
