export const APP_GET_LOGIN = 'APP_GET_LOGIN';
export const APP_GET_API_KEYS = 'APP_GET_API_KEYS';
export const APP_GET_FORGOT_PASSWORD = 'APP_GET_FORGOT_PASSWORD';
export const SETTINGS_GET_USER_SETTINGS = 'SETTINGS_GET_USER_SETTINGS';
export const SETTINGS_REMOVE_USER_DEVICE = 'SETTINGS_REMOVE_USER_DEVICE';
export const SETTINGS_ADD_USER_DEVICE = 'SETTINGS_ADD_USER_DEVICE';
export const APP_GET_CHANGE_PASSWORD = 'APP_GET_CHANGE_PASSWORD';
export const APP_GET_SIGNUP = 'APP_GET_SIGNUP';
