import _ from 'lodash';

export default _.mapKeys([
  'APP_GET_LOGIN',
  'APP_GET_API_KEYS',
  'SETTINGS_GET_USER_SETTINGS',
  'SETTINGS_REMOVE_USER_DEVICE',
  'SETTINGS_ADD_USER_DEVICE',
  'APP_GET_CHANGE_PASSWORD',
]);
