import _ from 'lodash';

export default _.mapKeys([
  'APP_GET_LOGIN',
  'APP_GET_API_KEYS',
  'APP_GET_FORGOT_PASSWORD',
  'SETTINGS_GET_USER_SETTINGS',
  'SETTINGS_REMOVE_USER_DEVICE',
  'SETTINGS_ADD_USER_DEVICE',
  'APP_GET_CHANGE_PASSWORD',
  'APP_GET_SIGNUP',
  'MESSAGES_MARK_ALL_READ',
  'MESSAGES_CREATE_USER_MESSAGE',
  'MESSAGES_CREATE_SUSI_MESSAGE',
  'MESSAGES_CREATE_HISTORY_MESSAGES',
  'MESSAGES_RESET_MESSAGE_VOICE',
  'MESSAGES_FEEDBACK_RECEIVED',
  'MESSAGES_INIT_TTS_VOICES',
  'MESSAGES_GET_HISTORY_FROM_SERVER',
]);
