export default [
  'CLICK_THREAD',
  'CREATE_MESSAGE',
  'RECEIVE_RAW_CREATED_MESSAGE',
  'CREATE_SUSI_MESSAGE',
  'STORE_HISTORY_MESSAGE',
  'RESET_MESSAGE_VOICE',
  'FEEDBACK_RECEIVED',
  'INIT_TTS_VOICES',
];
